defaults:
  - default

_transform:
  docking_score:
    _target_: ppiformer.data.transforms.DockingScorePretransform
    csv_file_path:
      _target_: hydra.utils.get_object
      path: ppiref.definitions.PPIREF_BM5_CSV_PATH
