# @package _global_

defaults:
  - _self_
  - model: ???
  - dataloader@train_dataloader:
    - train
    - ssl
  - dataloader@val_dataloader: 
    - val
    - ssl
    - ddg_regression_val
  - trainer: cpu
  - experiment: null
  - override hydra/launcher: slurm  # --multirun required to use

train_dataloader:
  dataset: "dips_equidock_cleaned,8"
val_dataloader:
  dataset: "skempi2_V3_split,8"

# wandb params
team_name: "ppiformer"
project_name: "NO_NAME"
run_name: ""
tags: []  # override with just a string with comma-separated tags
job_key: null  # used as slurm job name and wand run_id. Override to resume run
resume_job_key: null

cv: false
resume: false

seed: 3721

# TODO Remove and create separate test.py
test: false  # set to true to just run a test on validation data
